{
  "error": {
    "message": "An error occurred while fetching external data.",
    "url": "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_hubv/FeatureServer/0/query?where=NeuGenesen IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdLandkreis,Datenstand&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis&groupByFieldsForStatistics=IdLandkreis,Datenstand&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token=",
    "details": "connect ETIMEDOUT 18.65.229.60:443",
    "stack": "Error: connect ETIMEDOUT 18.65.229.60:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"
  }
}
